[build-system]
requires = [
  "setuptools>=77",
  "wheel",
  "packaging>=24.2"
]
build-backend = "setuptools.build_meta"

[project]
name = "epaper-calendar"
version = "1.0.0"
description = "An e paper calendar"
readme = "README.md"
requires-python = ">=3.9.2"
license = "MIT"
authors = [
  {name = "Travis Dixon", email = "the.trav@gmail.com"},
  {name = "Beth Skurrie", email = "beth@bethesque.com"},
]
keywords = []

# Main project dependencies (replaces requirements.txt)
dependencies = [
    "google-api-python-client==2.99.0",
    "google-auth-httplib2==0.1.1",
    "google-auth-oauthlib==1.1.0",
    "Pillow==11.1.0",
    "qrcode==7.4.2",
    "CherryPy==18.10.0",
    "requests==2.31.0",
    "tzdata",
    "mutagen==1.47.0",
    "gtts==2.5.4",
]

[project.optional-dependencies]
# Extra dependencies installed via `pip install ".[dev]"`
dev = [
    "black",
]

[project.urls]
# Links displayed on PyPI
Homepage = "https://github.com/thetrav/calendar"

[project.scripts]
# Creates a command line tool called 'my-tool' that runs the 'main' function
ecal-alarm-stop = "ecal.alarms.cli:stop_alarm"
ecal-alarm-test = "ecal.alarms.cli:test_alarm"
ecal-data-refresh = "ecal.cli:refresh_calendar_data"
ecal-screen-clear = "ecal.screen.cli:clear_screen"

[tool.setuptools]
# Tells setuptools where to find your source code
packages = ["ecal", "waveshare_epd"]

[tool.pytest.ini_options]
# Configuration for other tools (like pytest) can also live here
testpaths = ["tests"]
